"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-12 02:37:39.471876
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_events")),
    )
    op.create_table(
        "canonical_heroes",
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("hero_id", name=op.f("pk_canonical_heroes")),
    )
    op.create_table(
        "canonical_players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_players")),
        sa.UniqueConstraint("account_id", name=op.f("uq_canonical_players_account_id")),
    )
    op.create_table(
        "canonical_teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_teams")),
    )
    op.create_table(
        "domain_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_events")),
        sa.UniqueConstraint("event_type", "dedupe_key", name="uq_domain_event_dedupe"),
    )
    op.create_index(
        "ix_domain_event_pending", "domain_events", ["processed_at", "occurred_at"], unique=False
    )
    op.create_table(
        "durable_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("dedupe_key", sa.String(length=255), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_durable_jobs")),
        sa.UniqueConstraint("job_type", "dedupe_key", name="uq_durable_job_dedupe"),
    )
    op.create_index(
        "ix_durable_job_claim", "durable_jobs", ["status", "priority", "not_before"], unique=False
    )
    op.create_index("ix_durable_job_lease", "durable_jobs", ["status", "locked_at"], unique=False)
    op.create_table(
        "feature_snapshot_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("feature_type", sa.String(length=64), nullable=False),
        sa.Column("feature_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_match_id", sa.String(length=128), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=False),
        sa.Column("first_usable_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_snapshot_sources")),
    )
    op.create_index(
        op.f("ix_feature_snapshot_sources_feature_snapshot_id"),
        "feature_snapshot_sources",
        ["feature_snapshot_id"],
        unique=False,
    )
    op.create_table(
        "provider_raw_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("provider_key", sa.String(length=255), nullable=True),
        sa.Column("request_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", "received_at", name=op.f("pk_provider_raw_events")),
        postgresql_partition_by="RANGE (received_at)",
    )
    op.create_index(
        "ix_raw_provider_key_received",
        "provider_raw_events",
        ["provider", "provider_key", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_raw_received_brin",
        "provider_raw_events",
        ["received_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "raybet_matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_match_id", sa.BigInteger(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("tournament_id", sa.BigInteger(), nullable=True),
        sa.Column("tournament_name", sa.String(length=255), nullable=True),
        sa.Column("team_a_provider_id", sa.BigInteger(), nullable=False),
        sa.Column("team_a_name", sa.String(length=255), nullable=False),
        sa.Column("team_b_provider_id", sa.BigInteger(), nullable=False),
        sa.Column("team_b_name", sa.String(length=255), nullable=False),
        sa.Column("round", sa.String(length=64), nullable=True),
        sa.Column("raw_status", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raybet_matches")),
    )
    op.create_index(
        "ix_raybet_match_observed",
        "raybet_matches",
        ["provider_match_id", "observed_at"],
        unique=False,
    )
    op.create_table(
        "raybet_odds_registry",
        sa.Column("odds_id", sa.BigInteger(), nullable=False),
        sa.Column("provider_match_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=True),
        sa.Column("team_name", sa.String(length=255), nullable=True),
        sa.Column("group_short_name", sa.String(length=128), nullable=True),
        sa.Column("match_stage", sa.String(length=64), nullable=True),
        sa.Column("raw_status", sa.Integer(), nullable=True),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("odds_id", name=op.f("pk_raybet_odds_registry")),
    )
    op.create_index(
        op.f("ix_raybet_odds_registry_provider_match_id"),
        "raybet_odds_registry",
        ["provider_match_id"],
        unique=False,
    )
    op.create_table(
        "role_metric_baselines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patch_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(length=64), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("std", sa.Float(), nullable=True),
        sa.Column("median", sa.Float(), nullable=True),
        sa.Column("p25", sa.Float(), nullable=True),
        sa.Column("p75", sa.Float(), nullable=True),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_metric_baselines")),
        sa.UniqueConstraint(
            "patch_id", "position", "metric", "knowledge_cutoff", name="uq_role_baseline_cutoff"
        ),
    )
    op.create_index(
        "ix_role_baseline_asof",
        "role_metric_baselines",
        ["patch_id", "position", "knowledge_cutoff"],
        unique=False,
    )
    op.create_table(
        "worker_checkpoints",
        sa.Column("worker_name", sa.String(length=128), nullable=False),
        sa.Column(
            "checkpoint",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_name", name=op.f("pk_worker_checkpoints")),
    )
    op.create_table(
        "canonical_series",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("team_a_id", sa.Uuid(), nullable=False),
        sa.Column("team_b_id", sa.Uuid(), nullable=False),
        sa.Column("best_of", sa.Integer(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["canonical_events.id"],
            name=op.f("fk_canonical_series_event_id_canonical_events"),
        ),
        sa.ForeignKeyConstraint(
            ["team_a_id"],
            ["canonical_teams.id"],
            name=op.f("fk_canonical_series_team_a_id_canonical_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["team_b_id"],
            ["canonical_teams.id"],
            name=op.f("fk_canonical_series_team_b_id_canonical_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_series")),
    )
    op.create_table(
        "job_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["durable_jobs.id"], name=op.f("fk_job_attempts_job_id_durable_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_attempts")),
        sa.UniqueConstraint("job_id", "attempt_number", name="uq_job_attempt_number"),
    )
    op.create_index(
        "ix_job_attempt_started", "job_attempts", ["job_id", "started_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("domain_event_id", sa.Uuid(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["domain_event_id"],
            ["domain_events.id"],
            name=op.f("fk_outbox_events_domain_event_id_domain_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint("domain_event_id", "topic", name="uq_outbox_event_topic"),
    )
    op.create_index(
        "ix_outbox_pending", "outbox_events", ["published_at", "created_at"], unique=False
    )
    op.create_table(
        "provider_player_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_player_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_player_id", sa.Uuid(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_player_id"],
            ["canonical_players.id"],
            name=op.f("fk_provider_player_mappings_canonical_player_id_canonical_players"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_player_mappings")),
        sa.UniqueConstraint("provider", "provider_player_id", name="uq_provider_player_identity"),
    )
    op.create_table(
        "provider_team_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_team_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_team_id", sa.Uuid(), nullable=False),
        sa.Column("observed_name", sa.String(length=255), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_provider_team_mappings_canonical_team_id_canonical_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_team_mappings")),
        sa.UniqueConstraint("provider", "provider_team_id", name="uq_provider_team_identity"),
    )
    op.create_table(
        "team_form_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_team_id", sa.Uuid(), nullable=False),
        sa.Column("last_5_maps", sa.Integer(), nullable=False),
        sa.Column("last_5_wins", sa.Integer(), nullable=False),
        sa.Column("last_10_maps", sa.Integer(), nullable=False),
        sa.Column("last_10_wins", sa.Integer(), nullable=False),
        sa.Column("last_20_maps", sa.Integer(), nullable=False),
        sa.Column("last_20_wins", sa.Integer(), nullable=False),
        sa.Column("recent_form", sa.Float(), nullable=True),
        sa.Column("exact_roster_maps", sa.Integer(), nullable=False),
        sa.Column("roster_stability", sa.Float(), nullable=True),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_team_form_snapshots_canonical_team_id_canonical_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_form_snapshots")),
    )
    op.create_index(
        "ix_team_form_asof",
        "team_form_snapshots",
        ["canonical_team_id", "knowledge_cutoff"],
        unique=False,
    )
    op.create_table(
        "canonical_maps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=True),
        sa.Column("map_number", sa.Integer(), nullable=True),
        sa.Column("valve_match_id", sa.BigInteger(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["canonical_series.id"],
            name=op.f("fk_canonical_maps_series_id_canonical_series"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_maps")),
        sa.UniqueConstraint("series_id", "map_number", name="uq_canonical_maps_series_map"),
        sa.UniqueConstraint("valve_match_id", name=op.f("uq_canonical_maps_valve_match_id")),
    )
    op.create_table(
        "decision_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=True),
        sa.Column("decision_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column(
            "canonical_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("snapshot_hash", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_decision_snapshots_canonical_map_id_canonical_maps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_snapshots")),
        sa.UniqueConstraint("snapshot_hash", name=op.f("uq_decision_snapshots_snapshot_hash")),
    )
    op.create_index(
        "ix_decision_map_time",
        "decision_snapshots",
        ["canonical_map_id", "decision_at"],
        unique=False,
    )
    op.create_table(
        "dltv_live_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=True),
        sa.Column("valve_match_id", sa.BigInteger(), nullable=False),
        sa.Column("game_time_seconds", sa.Integer(), nullable=True),
        sa.Column("radiant_kills", sa.Integer(), nullable=True),
        sa.Column("dire_kills", sa.Integer(), nullable=True),
        sa.Column("radiant_nw_lead", sa.Integer(), nullable=True),
        sa.Column("first_blood", sa.String(length=32), nullable=True),
        sa.Column("source_game_time", sa.Integer(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_dltv_live_observations_canonical_map_id_canonical_maps"),
        ),
        sa.PrimaryKeyConstraint("id", "received_at", name=op.f("pk_dltv_live_observations")),
        sa.UniqueConstraint(
            "valve_match_id", "payload_hash", "received_at", name="uq_dltv_normalized_state"
        ),
        postgresql_partition_by="RANGE (received_at)",
    )
    op.create_index(
        "ix_dltv_map_received",
        "dltv_live_observations",
        ["canonical_map_id", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_dltv_received_brin",
        "dltv_live_observations",
        ["received_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "draft_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=False),
        sa.Column("valve_match_id", sa.BigInteger(), nullable=False),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column(
            "blockers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "warnings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("payload_hash", sa.String(length=128), nullable=False),
        sa.Column("statistics_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_draft_snapshots_canonical_map_id_canonical_maps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_snapshots")),
    )
    op.create_index(
        "ix_draft_map_cutoff",
        "draft_snapshots",
        ["canonical_map_id", "statistics_cutoff"],
        unique=False,
    )
    op.create_table(
        "historical_maps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_match_id", sa.String(length=128), nullable=False),
        sa.Column("patch_id", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("winner_team_id", sa.Uuid(), nullable=True),
        sa.Column("first_usable_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("basic_ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("advanced_ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_status", sa.String(length=32), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_historical_maps_canonical_map_id_canonical_maps"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_historical_maps_winner_team_id_canonical_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_maps")),
        sa.UniqueConstraint("provider", "provider_match_id", name="uq_historical_provider_match"),
    )
    op.create_index(
        "ix_historical_map_usable", "historical_maps", ["first_usable_at"], unique=False
    )
    op.create_table(
        "live_sync_estimates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=False),
        sa.Column("estimated_lag_seconds", sa.Float(), nullable=True),
        sa.Column("p50_seconds", sa.Float(), nullable=True),
        sa.Column("p90_seconds", sa.Float(), nullable=True),
        sa.Column("jitter_seconds", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_live_sync_estimates_canonical_map_id_canonical_maps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_sync_estimates")),
    )
    op.create_index(
        "ix_live_sync_map_time",
        "live_sync_estimates",
        ["canonical_map_id", "calculated_at"],
        unique=False,
    )
    op.create_table(
        "map_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=False),
        sa.Column("winner_team_id", sa.Uuid(), nullable=True),
        sa.Column("basic_first_usable_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("advanced_first_usable_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_conflict", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_map_results_canonical_map_id_canonical_maps"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_map_results_winner_team_id_canonical_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_results")),
        sa.UniqueConstraint("canonical_map_id", name=op.f("uq_map_results_canonical_map_id")),
    )
    op.create_table(
        "odds_observations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_match_id", sa.BigInteger(), nullable=False),
        sa.Column("odds_id", sa.BigInteger(), nullable=False),
        sa.Column("canonical_series_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=True),
        sa.Column("market_type", sa.String(length=128), nullable=True),
        sa.Column("match_stage", sa.String(length=64), nullable=True),
        sa.Column("selection_team_id", sa.Uuid(), nullable=True),
        sa.Column("price", sa.Numeric(precision=12, scale=5), nullable=False),
        sa.Column("implied_probability", sa.Float(), nullable=False),
        sa.Column("fair_probability", sa.Float(), nullable=True),
        sa.Column("overround", sa.Float(), nullable=True),
        sa.Column("raw_status", sa.Integer(), nullable=True),
        sa.Column("normalized_status", sa.String(length=32), nullable=True),
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_event_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_odds_observations_canonical_map_id_canonical_maps"),
        ),
        sa.ForeignKeyConstraint(
            ["canonical_series_id"],
            ["canonical_series.id"],
            name=op.f("fk_odds_observations_canonical_series_id_canonical_series"),
        ),
        sa.ForeignKeyConstraint(
            ["selection_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_odds_observations_selection_team_id_canonical_teams"),
        ),
        sa.PrimaryKeyConstraint("id", "received_at", name=op.f("pk_odds_observations")),
        postgresql_partition_by="RANGE (received_at)",
    )
    op.create_index(
        "ix_odds_id_provider_time",
        "odds_observations",
        ["odds_id", "provider_updated_at"],
        unique=False,
    )
    op.create_index(
        "ix_odds_map_received",
        "odds_observations",
        ["canonical_map_id", "received_at"],
        unique=False,
    )
    op.create_index(
        "ix_odds_received_brin",
        "odds_observations",
        ["received_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "player_form_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_player_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("base_strength", sa.Float(), nullable=True),
        sa.Column("recent_5", sa.Float(), nullable=True),
        sa.Column("recent_10", sa.Float(), nullable=True),
        sa.Column("recent_20", sa.Float(), nullable=True),
        sa.Column("recent_form", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("last_included_map_id", sa.Uuid(), nullable=True),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_player_id"],
            ["canonical_players.id"],
            name=op.f("fk_player_form_snapshots_canonical_player_id_canonical_players"),
        ),
        sa.ForeignKeyConstraint(
            ["last_included_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_player_form_snapshots_last_included_map_id_canonical_maps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_form_snapshots")),
    )
    op.create_index(
        "ix_player_form_asof",
        "player_form_snapshots",
        ["canonical_player_id", "position", "knowledge_cutoff"],
        unique=False,
    )
    op.create_table(
        "player_hero_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_player_id", sa.Uuid(), nullable=False),
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("historical_maps", sa.Integer(), nullable=False),
        sa.Column("historical_win_rate", sa.Float(), nullable=True),
        sa.Column("recent_180d_maps", sa.Integer(), nullable=False),
        sa.Column("recent_180d_win_rate", sa.Float(), nullable=True),
        sa.Column("current_patch_maps", sa.Integer(), nullable=False),
        sa.Column("current_patch_win_rate", sa.Float(), nullable=True),
        sa.Column("position_fit", sa.Float(), nullable=True),
        sa.Column("raw_strength", sa.Float(), nullable=True),
        sa.Column("adjusted_strength", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("last_included_map_id", sa.Uuid(), nullable=True),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_player_id"],
            ["canonical_players.id"],
            name=op.f("fk_player_hero_snapshots_canonical_player_id_canonical_players"),
        ),
        sa.ForeignKeyConstraint(
            ["last_included_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_player_hero_snapshots_last_included_map_id_canonical_maps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_hero_snapshots")),
    )
    op.create_index(
        "ix_player_hero_asof",
        "player_hero_snapshots",
        ["canonical_player_id", "hero_id", "position", "knowledge_cutoff"],
        unique=False,
    )
    op.create_table(
        "player_performance_maps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_player_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "metric_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("role_adjusted_score", sa.Float(), nullable=True),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_player_performance_maps_canonical_map_id_canonical_maps"),
        ),
        sa.ForeignKeyConstraint(
            ["canonical_player_id"],
            ["canonical_players.id"],
            name=op.f("fk_player_performance_maps_canonical_player_id_canonical_players"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_performance_maps")),
        sa.UniqueConstraint(
            "canonical_player_id", "canonical_map_id", name="uq_player_performance_map"
        ),
    )
    op.create_index(
        "ix_player_performance_asof",
        "player_performance_maps",
        ["canonical_player_id", "knowledge_cutoff"],
        unique=False,
    )
    op.create_table(
        "provider_match_mappings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_match_id", sa.String(length=128), nullable=False),
        sa.Column("canonical_series_id", sa.Uuid(), nullable=True),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=True),
        sa.Column("valve_match_id", sa.BigInteger(), nullable=True),
        sa.Column("resolved_by", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_provider_match_mappings_canonical_map_id_canonical_maps"),
        ),
        sa.ForeignKeyConstraint(
            ["canonical_series_id"],
            ["canonical_series.id"],
            name=op.f("fk_provider_match_mappings_canonical_series_id_canonical_series"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_match_mappings")),
        sa.UniqueConstraint("provider", "provider_match_id", name="uq_provider_match_identity"),
    )
    op.create_index(
        "ix_provider_match_valve_id", "provider_match_mappings", ["valve_match_id"], unique=False
    )
    op.create_table(
        "ai_decisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("request_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_seconds", sa.Float(), nullable=True),
        sa.Column(
            "raw_response",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "normalized_response",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["decision_snapshots.id"],
            name=op.f("fk_ai_decisions_snapshot_id_decision_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_decisions")),
        sa.UniqueConstraint("snapshot_id", "provider", name="uq_ai_provider_snapshot"),
    )
    op.create_index(
        "ix_ai_snapshot_provider", "ai_decisions", ["snapshot_hash", "provider"], unique=False
    )
    op.create_table(
        "decision_future_odds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("horizon_seconds", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("odds_a", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("odds_b", sa.Numeric(precision=12, scale=5), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_snapshot_id"],
            ["decision_snapshots.id"],
            name=op.f("fk_decision_future_odds_decision_snapshot_id_decision_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", "due_at", name=op.f("pk_decision_future_odds")),
        sa.UniqueConstraint(
            "decision_snapshot_id", "horizon_seconds", "due_at", name="uq_future_odds_horizon"
        ),
        postgresql_partition_by="RANGE (due_at)",
    )
    op.create_index(
        "ix_future_odds_due_brin",
        "decision_future_odds",
        ["due_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "draft_minute_curves",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_map_id", sa.Uuid(), nullable=False),
        sa.Column("draft_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "points",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "derived_features",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("statistics_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("data_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_map_id"],
            ["canonical_maps.id"],
            name=op.f("fk_draft_minute_curves_canonical_map_id_canonical_maps"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_snapshot_id"],
            ["draft_snapshots.id"],
            name=op.f("fk_draft_minute_curves_draft_snapshot_id_draft_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_minute_curves")),
    )
    op.create_index(
        "ix_draft_curve_map_cutoff",
        "draft_minute_curves",
        ["canonical_map_id", "statistics_cutoff"],
        unique=False,
    )
    op.create_table(
        "draft_slots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("draft_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.String(length=16), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.BigInteger(), nullable=True),
        sa.Column("canonical_player_id", sa.Uuid(), nullable=True),
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_player_id"],
            ["canonical_players.id"],
            name=op.f("fk_draft_slots_canonical_player_id_canonical_players"),
        ),
        sa.ForeignKeyConstraint(
            ["draft_snapshot_id"],
            ["draft_snapshots.id"],
            name=op.f("fk_draft_slots_draft_snapshot_id_draft_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_slots")),
        sa.UniqueConstraint("draft_snapshot_id", "side", "position", name="uq_draft_side_position"),
    )
    op.create_table(
        "historical_player_maps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("historical_map_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_player_id", sa.Uuid(), nullable=True),
        sa.Column("account_id", sa.BigInteger(), nullable=False),
        sa.Column("canonical_team_id", sa.Uuid(), nullable=True),
        sa.Column("opponent_team_id", sa.Uuid(), nullable=True),
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=True),
        sa.Column("deaths", sa.Integer(), nullable=True),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("gpm", sa.Float(), nullable=True),
        sa.Column("xpm", sa.Float(), nullable=True),
        sa.Column("networth", sa.Float(), nullable=True),
        sa.Column("last_hits", sa.Integer(), nullable=True),
        sa.Column("hero_damage", sa.Float(), nullable=True),
        sa.Column("tower_damage", sa.Float(), nullable=True),
        sa.Column("impact", sa.Float(), nullable=True),
        sa.Column("basic_first_usable_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("advanced_first_usable_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["canonical_player_id"],
            ["canonical_players.id"],
            name=op.f("fk_historical_player_maps_canonical_player_id_canonical_players"),
        ),
        sa.ForeignKeyConstraint(
            ["canonical_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_historical_player_maps_canonical_team_id_canonical_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["historical_map_id"],
            ["historical_maps.id"],
            name=op.f("fk_historical_player_maps_historical_map_id_historical_maps"),
        ),
        sa.ForeignKeyConstraint(
            ["opponent_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_historical_player_maps_opponent_team_id_canonical_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historical_player_maps")),
        sa.UniqueConstraint("historical_map_id", "account_id", name="uq_historical_map_player"),
    )
    op.create_table(
        "team_rating_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_team_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("rating_before", sa.Float(), nullable=False),
        sa.Column("opponent_rating_before", sa.Float(), nullable=False),
        sa.Column("expected_probability", sa.Float(), nullable=False),
        sa.Column("result", sa.Float(), nullable=False),
        sa.Column("source_map_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_team_id"],
            ["canonical_teams.id"],
            name=op.f("fk_team_rating_snapshots_canonical_team_id_canonical_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["source_map_id"],
            ["historical_maps.id"],
            name=op.f("fk_team_rating_snapshots_source_map_id_historical_maps"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_rating_snapshots")),
        sa.UniqueConstraint("canonical_team_id", "source_map_id", name="uq_team_rating_source"),
    )
    op.create_index(
        "ix_team_rating_asof",
        "team_rating_snapshots",
        ["canonical_team_id", "knowledge_cutoff"],
        unique=False,
    )
    op.create_table(
        "decision_evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("ai_decision_id", sa.Uuid(), nullable=False),
        sa.Column("result_correct", sa.Boolean(), nullable=True),
        sa.Column("brier_score", sa.Float(), nullable=True),
        sa.Column("log_loss", sa.Float(), nullable=True),
        sa.Column("clv", sa.Float(), nullable=True),
        sa.Column("future_odds_direction", sa.String(length=32), nullable=True),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metrics_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_decision_id"],
            ["ai_decisions.id"],
            name=op.f("fk_decision_evaluations_ai_decision_id_ai_decisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_decision_evaluations")),
        sa.UniqueConstraint("ai_decision_id", name="uq_evaluation_ai_decision"),
    )
    if op.get_bind().dialect.name == "postgresql":
        for parent in (
            "provider_raw_events",
            "odds_observations",
            "dltv_live_observations",
            "decision_future_odds",
        ):
            op.execute(sa.text(f"CREATE TABLE {parent}_default PARTITION OF {parent} DEFAULT"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("decision_evaluations")
    op.drop_index("ix_team_rating_asof", table_name="team_rating_snapshots")
    op.drop_table("team_rating_snapshots")
    op.drop_table("historical_player_maps")
    op.drop_table("draft_slots")
    op.drop_index("ix_draft_curve_map_cutoff", table_name="draft_minute_curves")
    op.drop_table("draft_minute_curves")
    op.drop_index(
        "ix_future_odds_due_brin", table_name="decision_future_odds", postgresql_using="brin"
    )
    op.drop_table("decision_future_odds")
    op.drop_index("ix_ai_snapshot_provider", table_name="ai_decisions")
    op.drop_table("ai_decisions")
    op.drop_index("ix_provider_match_valve_id", table_name="provider_match_mappings")
    op.drop_table("provider_match_mappings")
    op.drop_index("ix_player_performance_asof", table_name="player_performance_maps")
    op.drop_table("player_performance_maps")
    op.drop_index("ix_player_hero_asof", table_name="player_hero_snapshots")
    op.drop_table("player_hero_snapshots")
    op.drop_index("ix_player_form_asof", table_name="player_form_snapshots")
    op.drop_table("player_form_snapshots")
    op.drop_index("ix_odds_received_brin", table_name="odds_observations", postgresql_using="brin")
    op.drop_index("ix_odds_map_received", table_name="odds_observations")
    op.drop_index("ix_odds_id_provider_time", table_name="odds_observations")
    op.drop_table("odds_observations")
    op.drop_table("map_results")
    op.drop_index("ix_live_sync_map_time", table_name="live_sync_estimates")
    op.drop_table("live_sync_estimates")
    op.drop_index("ix_historical_map_usable", table_name="historical_maps")
    op.drop_table("historical_maps")
    op.drop_index("ix_draft_map_cutoff", table_name="draft_snapshots")
    op.drop_table("draft_snapshots")
    op.drop_index(
        "ix_dltv_received_brin", table_name="dltv_live_observations", postgresql_using="brin"
    )
    op.drop_index("ix_dltv_map_received", table_name="dltv_live_observations")
    op.drop_table("dltv_live_observations")
    op.drop_index("ix_decision_map_time", table_name="decision_snapshots")
    op.drop_table("decision_snapshots")
    op.drop_table("canonical_maps")
    op.drop_index("ix_team_form_asof", table_name="team_form_snapshots")
    op.drop_table("team_form_snapshots")
    op.drop_table("provider_team_mappings")
    op.drop_table("provider_player_mappings")
    op.drop_index("ix_outbox_pending", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_job_attempt_started", table_name="job_attempts")
    op.drop_table("job_attempts")
    op.drop_table("canonical_series")
    op.drop_table("worker_checkpoints")
    op.drop_index("ix_role_baseline_asof", table_name="role_metric_baselines")
    op.drop_table("role_metric_baselines")
    op.drop_index(
        op.f("ix_raybet_odds_registry_provider_match_id"), table_name="raybet_odds_registry"
    )
    op.drop_table("raybet_odds_registry")
    op.drop_index("ix_raybet_match_observed", table_name="raybet_matches")
    op.drop_table("raybet_matches")
    op.drop_index("ix_raw_received_brin", table_name="provider_raw_events", postgresql_using="brin")
    op.drop_index("ix_raw_provider_key_received", table_name="provider_raw_events")
    op.drop_table("provider_raw_events")
    op.drop_index(
        op.f("ix_feature_snapshot_sources_feature_snapshot_id"),
        table_name="feature_snapshot_sources",
    )
    op.drop_table("feature_snapshot_sources")
    op.drop_index("ix_durable_job_lease", table_name="durable_jobs")
    op.drop_index("ix_durable_job_claim", table_name="durable_jobs")
    op.drop_table("durable_jobs")
    op.drop_index("ix_domain_event_pending", table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_table("canonical_teams")
    op.drop_table("canonical_players")
    op.drop_table("canonical_heroes")
    op.drop_table("canonical_events")
    # ### end Alembic commands ###
